export let emojiArray = [
	{
		emoji: '😀',
		description: 'grinning face',
		category: 'Smileys & Emotion',
		aliases: ['grinning'],
		tags: ['smile', 'happy'],
		unicode_version: '6.1',
		ios_version: '6.0',
	},
	{
		emoji: '😃',
		description: 'grinning face with big eyes',
		category: 'Smileys & Emotion',
		aliases: ['smiley'],
		tags: ['happy', 'joy', 'haha'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😄',
		description: 'grinning face with smiling eyes',
		category: 'Smileys & Emotion',
		aliases: ['smile'],
		tags: ['happy', 'joy', 'laugh', 'pleased'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😁',
		description: 'beaming face with smiling eyes',
		category: 'Smileys & Emotion',
		aliases: ['grin'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😆',
		description: 'grinning squinting face',
		category: 'Smileys & Emotion',
		aliases: ['laughing', 'satisfied'],
		tags: ['happy', 'haha'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😅',
		description: 'grinning face with sweat',
		category: 'Smileys & Emotion',
		aliases: ['sweat_smile'],
		tags: ['hot'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🤣',
		description: 'rolling on the floor laughing',
		category: 'Smileys & Emotion',
		aliases: ['rofl'],
		tags: ['lol', 'laughing'],
		unicode_version: '9.0',
		ios_version: '10.2',
	},
	{
		emoji: '😂',
		description: 'face with tears of joy',
		category: 'Smileys & Emotion',
		aliases: ['joy'],
		tags: ['tears'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🙂',
		description: 'slightly smiling face',
		category: 'Smileys & Emotion',
		aliases: ['slightly_smiling_face'],
		tags: [],
		unicode_version: '7.0',
		ios_version: '9.1',
	},
	{
		emoji: '🙃',
		description: 'upside-down face',
		category: 'Smileys & Emotion',
		aliases: ['upside_down_face'],
		tags: [],
		unicode_version: '8.0',
		ios_version: '9.1',
	},
	{
		emoji: '😉',
		description: 'winking face',
		category: 'Smileys & Emotion',
		aliases: ['wink'],
		tags: ['flirt'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😊',
		description: 'smiling face with smiling eyes',
		category: 'Smileys & Emotion',
		aliases: ['blush'],
		tags: ['proud'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😇',
		description: 'smiling face with halo',
		category: 'Smileys & Emotion',
		aliases: ['innocent'],
		tags: ['angel'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🥰',
		description: 'smiling face with hearts',
		category: 'Smileys & Emotion',
		aliases: ['smiling_face_with_three_hearts'],
		tags: ['love'],
		unicode_version: '11.0',
		ios_version: '12.1',
	},
	{
		emoji: '😍',
		description: 'smiling face with heart-eyes',
		category: 'Smileys & Emotion',
		aliases: ['heart_eyes'],
		tags: ['love', 'crush'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🤩',
		description: 'star-struck',
		category: 'Smileys & Emotion',
		aliases: ['star_struck'],
		tags: ['eyes'],
		unicode_version: '11.0',
		ios_version: '12.1',
	},
	{
		emoji: '😘',
		description: 'face blowing a kiss',
		category: 'Smileys & Emotion',
		aliases: ['kissing_heart'],
		tags: ['flirt'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😗',
		description: 'kissing face',
		category: 'Smileys & Emotion',
		aliases: ['kissing'],
		tags: [],
		unicode_version: '6.1',
		ios_version: '6.0',
	},
	{
		emoji: '😚',
		description: 'kissing face with closed eyes',
		category: 'Smileys & Emotion',
		aliases: ['kissing_closed_eyes'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😙',
		description: 'kissing face with smiling eyes',
		category: 'Smileys & Emotion',
		aliases: ['kissing_smiling_eyes'],
		tags: [],
		unicode_version: '6.1',
		ios_version: '6.0',
	},
	{
		emoji: '😋',
		description: 'face savoring food',
		category: 'Smileys & Emotion',
		aliases: ['yum'],
		tags: ['tongue', 'lick'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😛',
		description: 'face with tongue',
		category: 'Smileys & Emotion',
		aliases: ['stuck_out_tongue'],
		tags: [],
		unicode_version: '6.1',
		ios_version: '6.0',
	},
	{
		emoji: '😜',
		description: 'winking face with tongue',
		category: 'Smileys & Emotion',
		aliases: ['stuck_out_tongue_winking_eye'],
		tags: ['prank', 'silly'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🤪',
		description: 'zany face',
		category: 'Smileys & Emotion',
		aliases: ['zany_face'],
		tags: ['goofy', 'wacky'],
		unicode_version: '11.0',
		ios_version: '12.1',
	},
	{
		emoji: '😝',
		description: 'squinting face with tongue',
		category: 'Smileys & Emotion',
		aliases: ['stuck_out_tongue_closed_eyes'],
		tags: ['prank'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🤑',
		description: 'money-mouth face',
		category: 'Smileys & Emotion',
		aliases: ['money_mouth_face'],
		tags: ['rich'],
		unicode_version: '8.0',
		ios_version: '9.1',
	},
	{
		emoji: '🤗',
		description: 'smiling face with open hands',
		category: 'Smileys & Emotion',
		aliases: ['hugs'],
		tags: [],
		unicode_version: '8.0',
		ios_version: '9.1',
	},
	{
		emoji: '🤭',
		description: 'face with hand over mouth',
		category: 'Smileys & Emotion',
		aliases: ['hand_over_mouth'],
		tags: ['quiet', 'whoops'],
		unicode_version: '11.0',
		ios_version: '12.1',
	},
	{
		emoji: '🤫',
		description: 'shushing face',
		category: 'Smileys & Emotion',
		aliases: ['shushing_face'],
		tags: ['silence', 'quiet'],
		unicode_version: '11.0',
		ios_version: '12.1',
	},
	{
		emoji: '🤔',
		description: 'thinking face',
		category: 'Smileys & Emotion',
		aliases: ['thinking'],
		tags: [],
		unicode_version: '8.0',
		ios_version: '9.1',
	},
	{
		emoji: '🤐',
		description: 'zipper-mouth face',
		category: 'Smileys & Emotion',
		aliases: ['zipper_mouth_face'],
		tags: ['silence', 'hush'],
		unicode_version: '8.0',
		ios_version: '9.1',
	},
	{
		emoji: '🤨',
		description: 'face with raised eyebrow',
		category: 'Smileys & Emotion',
		aliases: ['raised_eyebrow'],
		tags: ['suspicious'],
		unicode_version: '11.0',
		ios_version: '12.1',
	},
	{
		emoji: '😐',
		description: 'neutral face',
		category: 'Smileys & Emotion',
		aliases: ['neutral_face'],
		tags: ['meh'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😑',
		description: 'expressionless face',
		category: 'Smileys & Emotion',
		aliases: ['expressionless'],
		tags: [],
		unicode_version: '6.1',
		ios_version: '6.0',
	},
	{
		emoji: '😶',
		description: 'face without mouth',
		category: 'Smileys & Emotion',
		aliases: ['no_mouth'],
		tags: ['mute', 'silence'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😏',
		description: 'smirking face',
		category: 'Smileys & Emotion',
		aliases: ['smirk'],
		tags: ['smug'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😒',
		description: 'unamused face',
		category: 'Smileys & Emotion',
		aliases: ['unamused'],
		tags: ['meh'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🙄',
		description: 'face with rolling eyes',
		category: 'Smileys & Emotion',
		aliases: ['roll_eyes'],
		tags: [],
		unicode_version: '8.0',
		ios_version: '9.1',
	},
	{
		emoji: '😬',
		description: 'grimacing face',
		category: 'Smileys & Emotion',
		aliases: ['grimacing'],
		tags: [],
		unicode_version: '6.1',
		ios_version: '6.0',
	},
	{
		emoji: '🤤',
		description: 'drooling face',
		category: 'Smileys & Emotion',
		aliases: ['drooling_face'],
		tags: [],
		unicode_version: '9.0',
		ios_version: '10.2',
	},
	{
		emoji: '🤠',
		description: 'cowboy hat face',
		category: 'Smileys & Emotion',
		aliases: ['cowboy_hat_face'],
		tags: [],
		unicode_version: '9.0',
		ios_version: '10.2',
	},
	{
		emoji: '🥳',
		description: 'partying face',
		category: 'Smileys & Emotion',
		aliases: ['partying_face'],
		tags: ['celebration', 'birthday'],
		unicode_version: '11.0',
		ios_version: '12.1',
	},
	{
		emoji: '😎',
		description: 'smiling face with sunglasses',
		category: 'Smileys & Emotion',
		aliases: ['sunglasses'],
		tags: ['cool'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🤓',
		description: 'nerd face',
		category: 'Smileys & Emotion',
		aliases: ['nerd_face'],
		tags: ['geek', 'glasses'],
		unicode_version: '8.0',
		ios_version: '9.1',
	},
	{
		emoji: '🧐',
		description: 'face with monocle',
		category: 'Smileys & Emotion',
		aliases: ['monocle_face'],
		tags: [],
		unicode_version: '11.0',
		ios_version: '12.1',
	},
	{
		emoji: '😕',
		description: 'confused face',
		category: 'Smileys & Emotion',
		aliases: ['confused'],
		tags: [],
		unicode_version: '6.1',
		ios_version: '6.0',
	},
	{
		emoji: '😧',
		description: 'anguished face',
		category: 'Smileys & Emotion',
		aliases: ['anguished'],
		tags: ['stunned'],
		unicode_version: '6.1',
		ios_version: '6.0',
	},
	{
		emoji: '😨',
		description: 'fearful face',
		category: 'Smileys & Emotion',
		aliases: ['fearful'],
		tags: ['scared', 'shocked', 'oops'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😰',
		description: 'anxious face with sweat',
		category: 'Smileys & Emotion',
		aliases: ['cold_sweat'],
		tags: ['nervous'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😥',
		description: 'sad but relieved face',
		category: 'Smileys & Emotion',
		aliases: ['disappointed_relieved'],
		tags: ['phew', 'sweat', 'nervous'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😢',
		description: 'crying face',
		category: 'Smileys & Emotion',
		aliases: ['cry'],
		tags: ['sad', 'tear'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😭',
		description: 'loudly crying face',
		category: 'Smileys & Emotion',
		aliases: ['sob'],
		tags: ['sad', 'cry', 'bawling'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😱',
		description: 'face screaming in fear',
		category: 'Smileys & Emotion',
		aliases: ['scream'],
		tags: ['horror', 'shocked'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😖',
		description: 'confounded face',
		category: 'Smileys & Emotion',
		aliases: ['confounded'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😣',
		description: 'persevering face',
		category: 'Smileys & Emotion',
		aliases: ['persevere'],
		tags: ['struggling'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😞',
		description: 'disappointed face',
		category: 'Smileys & Emotion',
		aliases: ['disappointed'],
		tags: ['sad'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😓',
		description: 'downcast face with sweat',
		category: 'Smileys & Emotion',
		aliases: ['sweat'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😩',
		description: 'weary face',
		category: 'Smileys & Emotion',
		aliases: ['weary'],
		tags: ['tired'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😫',
		description: 'tired face',
		category: 'Smileys & Emotion',
		aliases: ['tired_face'],
		tags: ['upset', 'whine'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🥱',
		description: 'yawning face',
		category: 'Smileys & Emotion',
		aliases: ['yawning_face'],
		tags: [],
		unicode_version: '12.0',
		ios_version: '13.0',
	},
	{
		emoji: '😤',
		description: 'face with steam from nose',
		category: 'Smileys & Emotion',
		aliases: ['triumph'],
		tags: ['smug'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😡',
		description: 'enraged face',
		category: 'Smileys & Emotion',
		aliases: ['rage', 'pout'],
		tags: ['angry'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😠',
		description: 'angry face',
		category: 'Smileys & Emotion',
		aliases: ['angry'],
		tags: ['mad', 'annoyed'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🤬',
		description: 'face with symbols on mouth',
		category: 'Smileys & Emotion',
		aliases: ['cursing_face'],
		tags: ['foul'],
		unicode_version: '11.0',
		ios_version: '12.1',
	},
	{
		emoji: '😈',
		description: 'smiling face with horns',
		category: 'Smileys & Emotion',
		aliases: ['smiling_imp'],
		tags: ['devil', 'evil', 'horns'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '👿',
		description: 'angry face with horns',
		category: 'Smileys & Emotion',
		aliases: ['imp'],
		tags: ['angry', 'devil', 'evil', 'horns'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '💀',
		description: 'skull',
		category: 'Smileys & Emotion',
		aliases: ['skull'],
		tags: ['dead', 'danger', 'poison'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '☠️',
		description: 'skull and crossbones',
		category: 'Smileys & Emotion',
		aliases: ['skull_and_crossbones'],
		tags: ['danger', 'pirate'],
		unicode_version: '',
		ios_version: '9.1',
	},
	{
		emoji: '🏆',
		description: 'skull and crossbones',
		category: 'Smileys & Emotion',
		aliases: ['skull_and_crossbones'],
		tags: ['danger', 'pirate'],
		unicode_version: '',
		ios_version: '9.1',
	},
	{
		emoji: '📈',
		description: 'skull and crossbones',
		category: 'Smileys & Emotion',
		aliases: ['skull_and_crossbones'],
		tags: ['danger', 'pirate'],
		unicode_version: '',
		ios_version: '9.1',
	},
	{
		emoji: '🌟',
		description: 'skull and crossbones',
		category: 'Smileys & Emotion',
		aliases: ['skull_and_crossbones'],
		tags: ['danger', 'pirate'],
		unicode_version: '',
		ios_version: '9.1',
	},
	{
		emoji: '🌞',
		description: 'skull and crossbones',
		category: 'Smileys & Emotion',
		aliases: ['skull_and_crossbones'],
		tags: ['danger', 'pirate'],
		unicode_version: '',
		ios_version: '9.1',
	},
	{
		emoji: '💐',
		description: 'skull and crossbones',
		category: 'Smileys & Emotion',
		aliases: ['skull_and_crossbones'],
		tags: ['danger', 'pirate'],
		unicode_version: '',
		ios_version: '9.1',
	},
	{
		emoji: '⚡',
		description: 'skull and crossbones',
		category: 'Smileys & Emotion',
		aliases: ['skull_and_crossbones'],
		tags: ['danger', 'pirate'],
		unicode_version: '',
		ios_version: '9.1',
	},
	{
		emoji: '🤡',
		description: 'clown face',
		category: 'Smileys & Emotion',
		aliases: ['clown_face'],
		tags: [],
		unicode_version: '9.0',
		ios_version: '10.2',
	},
	{
		emoji: '👹',
		description: 'ogre',
		category: 'Smileys & Emotion',
		aliases: ['japanese_ogre'],
		tags: ['monster'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '👺',
		description: 'goblin',
		category: 'Smileys & Emotion',
		aliases: ['japanese_goblin'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '👻',
		description: 'ghost',
		category: 'Smileys & Emotion',
		aliases: ['ghost'],
		tags: ['halloween'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '👽',
		description: 'alien',
		category: 'Smileys & Emotion',
		aliases: ['alien'],
		tags: ['ufo'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '👾',
		description: 'alien monster',
		category: 'Smileys & Emotion',
		aliases: ['space_invader'],
		tags: ['game', 'retro'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🤖',
		description: 'robot',
		category: 'Smileys & Emotion',
		aliases: ['robot'],
		tags: [],
		unicode_version: '8.0',
		ios_version: '9.1',
	},
	{
		emoji: '😺',
		description: 'grinning cat',
		category: 'Smileys & Emotion',
		aliases: ['smiley_cat'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😸',
		description: 'grinning cat with smiling eyes',
		category: 'Smileys & Emotion',
		aliases: ['smile_cat'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😹',
		description: 'cat with tears of joy',
		category: 'Smileys & Emotion',
		aliases: ['joy_cat'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😻',
		description: 'smiling cat with heart-eyes',
		category: 'Smileys & Emotion',
		aliases: ['heart_eyes_cat'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😼',
		description: 'cat with wry smile',
		category: 'Smileys & Emotion',
		aliases: ['smirk_cat'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😽',
		description: 'kissing cat',
		category: 'Smileys & Emotion',
		aliases: ['kissing_cat'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🙀',
		description: 'weary cat',
		category: 'Smileys & Emotion',
		aliases: ['scream_cat'],
		tags: ['horror'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😿',
		description: 'crying cat',
		category: 'Smileys & Emotion',
		aliases: ['crying_cat_face'],
		tags: ['sad', 'tear'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😾',
		description: 'pouting cat',
		category: 'Smileys & Emotion',
		aliases: ['pouting_cat'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🙈',
		description: 'see-no-evil monkey',
		category: 'Smileys & Emotion',
		aliases: ['see_no_evil'],
		tags: ['monkey', 'blind', 'ignore'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🙉',
		description: 'hear-no-evil monkey',
		category: 'Smileys & Emotion',
		aliases: ['hear_no_evil'],
		tags: ['monkey', 'deaf'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🙊',
		description: 'speak-no-evil monkey',
		category: 'Smileys & Emotion',
		aliases: ['speak_no_evil'],
		tags: ['monkey', 'mute', 'hush'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '💌',
		description: 'love letter',
		category: 'Smileys & Emotion',
		aliases: ['love_letter'],
		tags: ['email', 'envelope'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '💘',
		description: 'heart with arrow',
		category: 'Smileys & Emotion',
		aliases: ['cupid'],
		tags: ['love', 'heart'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '💝',
		description: 'heart with ribbon',
		category: 'Smileys & Emotion',
		aliases: ['gift_heart'],
		tags: ['chocolates'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '💖',
		description: 'sparkling heart',
		category: 'Smileys & Emotion',
		aliases: ['sparkling_heart'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '💗',
		description: 'growing heart',
		category: 'Smileys & Emotion',
		aliases: ['heartpulse'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '💓',
		description: 'beating heart',
		category: 'Smileys & Emotion',
		aliases: ['heartbeat'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '💞',
		description: 'revolving hearts',
		category: 'Smileys & Emotion',
		aliases: ['revolving_hearts'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '💕',
		description: 'two hearts',
		category: 'Smileys & Emotion',
		aliases: ['two_hearts'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '💟',
		description: 'heart decoration',
		category: 'Smileys & Emotion',
		aliases: ['heart_decoration'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '❣️',
		description: 'heart exclamation',
		category: 'Smileys & Emotion',
		aliases: ['heavy_heart_exclamation'],
		tags: [],
		unicode_version: '',
		ios_version: '9.1',
	},
	{
		emoji: '💔',
		description: 'broken heart',
		category: 'Smileys & Emotion',
		aliases: ['broken_heart'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '❤️',
		description: 'red heart',
		category: 'Smileys & Emotion',
		aliases: ['heart'],
		tags: ['love'],
		unicode_version: '',
		ios_version: '6.0',
	},
	{
		emoji: '🧡',
		description: 'orange heart',
		category: 'Smileys & Emotion',
		aliases: ['orange_heart'],
		tags: [],
		unicode_version: '11.0',
		ios_version: '12.1',
	},
	{
		emoji: '💛',
		description: 'yellow heart',
		category: 'Smileys & Emotion',
		aliases: ['yellow_heart'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '💚',
		description: 'green heart',
		category: 'Smileys & Emotion',
		aliases: ['green_heart'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '💙',
		description: 'blue heart',
		category: 'Smileys & Emotion',
		aliases: ['blue_heart'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '💋',
		description: 'kiss mark',
		category: 'Smileys & Emotion',
		aliases: ['kiss'],
		tags: ['lipstick'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '💯',
		description: 'hundred points',
		category: 'Smileys & Emotion',
		aliases: ['100'],
		tags: ['score', 'perfect'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🔥',
		description: 'hundred points',
		category: 'Smileys & Emotion',
		aliases: ['100'],
		tags: ['score', 'perfect'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '👋',
		description: 'waving hand',
		category: 'People & Body',
		aliases: ['wave'],
		tags: ['goodbye'],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: true,
	},
	{
		emoji: '🤚',
		description: 'raised back of hand',
		category: 'People & Body',
		aliases: ['raised_back_of_hand'],
		tags: [],
		unicode_version: '9.0',
		ios_version: '10.2',
		skin_tones: true,
	},
	{
		emoji: '🖐️',
		description: 'hand with fingers splayed',
		category: 'People & Body',
		aliases: ['raised_hand_with_fingers_splayed'],
		tags: [],
		unicode_version: '7.0',
		ios_version: '9.1',
		skin_tones: true,
	},
	{
		emoji: '✋',
		description: 'raised hand',
		category: 'People & Body',
		aliases: ['hand', 'raised_hand'],
		tags: ['highfive', 'stop'],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: true,
	},
	{
		emoji: '👌',
		description: 'OK hand',
		category: 'People & Body',
		aliases: ['ok_hand'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: true,
	},
	{
		emoji: '✌️',
		description: 'victory hand',
		category: 'People & Body',
		aliases: ['v'],
		tags: ['victory', 'peace'],
		unicode_version: '',
		ios_version: '6.0',
		skin_tones: true,
	},
	{
		emoji: '🤞',
		description: 'crossed fingers',
		category: 'People & Body',
		aliases: ['crossed_fingers'],
		tags: ['luck', 'hopeful'],
		unicode_version: '9.0',
		ios_version: '10.2',
		skin_tones: true,
	},
	{
		emoji: '🤟',
		description: 'love-you gesture',
		category: 'People & Body',
		aliases: ['love_you_gesture'],
		tags: [],
		unicode_version: '11.0',
		ios_version: '12.1',
		skin_tones: true,
	},
	{
		emoji: '👈',
		description: 'backhand index pointing left',
		category: 'People & Body',
		aliases: ['point_left'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: true,
	},
	{
		emoji: '👉',
		description: 'backhand index pointing right',
		category: 'People & Body',
		aliases: ['point_right'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: true,
	},
	{
		emoji: '👆',
		description: 'backhand index pointing up',
		category: 'People & Body',
		aliases: ['point_up_2'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: true,
	},
	{
		emoji: '👇',
		description: 'backhand index pointing down',
		category: 'People & Body',
		aliases: ['point_down'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: true,
	},
	{
		emoji: '☝️',
		description: 'index pointing up',
		category: 'People & Body',
		aliases: ['point_up'],
		tags: [],
		unicode_version: '',
		ios_version: '6.0',
		skin_tones: true,
	},
	{
		emoji: '👍',
		description: 'thumbs up',
		category: 'People & Body',
		aliases: ['+1', 'thumbsup'],
		tags: ['approve', 'ok'],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: true,
	},
	{
		emoji: '👎',
		description: 'thumbs down',
		category: 'People & Body',
		aliases: ['-1', 'thumbsdown'],
		tags: ['disapprove', 'bury'],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: true,
	},
	{
		emoji: '✊',
		description: 'raised fist',
		category: 'People & Body',
		aliases: ['fist_raised', 'fist'],
		tags: ['power'],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: true,
	},
	{
		emoji: '👊',
		description: 'oncoming fist',
		category: 'People & Body',
		aliases: ['fist_oncoming', 'facepunch', 'punch'],
		tags: ['attack'],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: true,
	},
	{
		emoji: '🙌',
		description: 'raising hands',
		category: 'People & Body',
		aliases: ['raised_hands'],
		tags: ['hooray'],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: true,
	},
	{
		emoji: '🤝',
		description: 'handshake',
		category: 'People & Body',
		aliases: ['handshake'],
		tags: ['deal'],
		unicode_version: '9.0',
		ios_version: '10.2',
		skin_tones: true,
	},
	{
		emoji: '🙏',
		description: 'folded hands',
		category: 'People & Body',
		aliases: ['pray'],
		tags: ['please', 'hope', 'wish'],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: true,
	},
	{
		emoji: '✍️',
		description: 'writing hand',
		category: 'People & Body',
		aliases: ['writing_hand'],
		tags: [],
		unicode_version: '',
		ios_version: '9.1',
		skin_tones: true,
	},
	{
		emoji: '🤳',
		description: 'selfie',
		category: 'People & Body',
		aliases: ['selfie'],
		tags: [],
		unicode_version: '9.0',
		ios_version: '10.2',
		skin_tones: true,
	},
	{
		emoji: '💪',
		description: 'flexed biceps',
		category: 'People & Body',
		aliases: ['muscle'],
		tags: ['flex', 'bicep', 'strong', 'workout'],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: true,
	},
];
